/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Design tokens — direct hex values for the competitive TCG/esports palette
        navy: {
          DEFAULT: '#061A45',
          50: '#E8EDF6',
          100: '#C5D0E8',
          200: '#9DB0D6',
          300: '#6E89BE',
          400: '#3F5FA3',
          500: '#052969',
          600: '#052969',
          700: '#061A45',
          800: '#04122E',
          900: '#020A1C',
        },
        blue: {
          DEFAULT: '#0A64C9',
          bright: '#1688F2',
          cyan: '#54C8FF',
          50: '#EAF4FE',
          100: '#D0E6FC',
          200: '#A6D2FA',
          300: '#6EB6F5',
          400: '#1688F2',
          500: '#0A64C9',
          600: '#0852A8',
          700: '#063E80',
          800: '#042B58',
          900: '#021A36',
        },
        gold: {
          DEFAULT: '#FFD323',
          light: '#FFEA68',
          dark: '#E6B800',
          50: '#FFFCEB',
          100: '#FFF7CC',
          200: '#FFEE99',
          300: '#FFE340',
          400: '#FFD323',
          500: '#E6B800',
          600: '#BF9900',
        },
        red: {
          DEFAULT: '#EF2328',
          accent: '#EF2328',
          50: '#FEEBEB',
          100: '#FDD0D0',
          200: '#FAA5A5',
          300: '#F27475',
          400: '#EF2328',
          500: '#D11E22',
          600: '#A8171A',
          700: '#7D1114',
        },
        surface: {
          light: '#F4F7FB',
          white: '#FFFFFF',
        },
        ink: {
          DEFAULT: '#0A1938',
          muted: '#687595',
        },
        line: {
          DEFAULT: '#D9E5F2',
          light: '#E8EFF7',
        },
        // Keep old tokens for backward compat during migration
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        success: {
          DEFAULT: 'hsl(var(--success))',
          foreground: 'hsl(var(--success-foreground))',
        },
        warning: {
          DEFAULT: 'hsl(var(--warning))',
          foreground: 'hsl(var(--warning-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        pokemon: {
          fire: 'hsl(var(--color-fire))',
          water: 'hsl(var(--color-water))',
          grass: 'hsl(var(--color-grass))',
          electric: 'hsl(var(--color-electric))',
          psychic: 'hsl(var(--color-psychic))',
          fighting: 'hsl(var(--color-fighting))',
          normal: 'hsl(var(--color-normal))',
          dragon: 'hsl(var(--color-dragon))',
          dark: 'hsl(var(--color-dark))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        xl: 'calc(var(--radius) + 4px)',
        '2xl': 'calc(var(--radius) + 8px)',
      },
      fontFamily: {
        rubik: ['Rubik', 'sans-serif'],
      },
      fontSize: {
        'display': ['3.5rem', { lineHeight: '1.05', fontWeight: '800' }],
        'display-sm': ['2.5rem', { lineHeight: '1.1', fontWeight: '800' }],
      },
      boxShadow: {
        'card': '0 2px 8px -2px rgba(6, 26, 69, 0.08), 0 1px 3px -1px rgba(6, 26, 69, 0.06)',
        'card-hover': '0 8px 24px -4px rgba(6, 26, 69, 0.12), 0 2px 8px -2px rgba(6, 26, 69, 0.08)',
        'glow-blue': '0 0 24px -4px rgba(22, 136, 242, 0.35)',
        'glow-gold': '0 0 20px -4px rgba(255, 211, 35, 0.4)',
        'glow-red': '0 0 16px -2px rgba(239, 35, 40, 0.35)',
        'cta': '0 4px 12px -2px rgba(255, 211, 35, 0.3), 0 2px 6px -1px rgba(6, 26, 69, 0.15)',
        'cta-hover': '0 6px 20px -2px rgba(255, 211, 35, 0.45), 0 4px 10px -1px rgba(6, 26, 69, 0.2)',
      },
      backgroundImage: {
        'hero-navy': 'radial-gradient(ellipse at 50% 0%, #052969 0%, #061A45 50%, #04122E 100%)',
        'hero-glow': 'radial-gradient(circle at 30% 40%, rgba(22, 136, 242, 0.15) 0%, transparent 50%), radial-gradient(circle at 70% 60%, rgba(84, 200, 255, 0.1) 0%, transparent 40%)',
        'section-light': 'linear-gradient(180deg, #FFFFFF 0%, #F4F7FB 100%)',
        'card-tint': 'linear-gradient(135deg, rgba(10, 100, 201, 0.03) 0%, rgba(84, 200, 255, 0.02) 100%)',
        'gold-gradient': 'linear-gradient(135deg, #FFD323 0%, #FFEA68 100%)',
        'blue-gradient': 'linear-gradient(135deg, #0A64C9 0%, #1688F2 100%)',
        'navy-gradient': 'linear-gradient(180deg, #061A45 0%, #052969 100%)',
        'red-gradient': 'linear-gradient(135deg, #EF2328 0%, #D11E22 100%)',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-out': {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        'slide-in': {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-up': {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'pulse-glow': {
          '0%, 100%': { opacity: '0.6' },
          '50%': { opacity: '1' },
        },
        'shimmer': {
          '0%': { backgroundPosition: '200% 0' },
          '100%': { backgroundPosition: '-200% 0' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.3s ease-in-out',
        'fade-out': 'fade-out 0.3s ease-in-out',
        'slide-in': 'slide-in 0.4s ease-out',
        'slide-up': 'slide-up 0.5s ease-out',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'shimmer': 'shimmer 3s linear infinite',
      },
    },
  },
  plugins: [],
};
